Update to 1.0-cl3u11 from CL Repo
http://repo3.cumulusnetworks.com/repo/pool/cumulus/v/vrf/
Signed-off-by: Jarad Olson <brotherdust+github@gmail.com>

diff --git a/debian/vrf.postinst b/debian/vrf.postinst
--- a/debian/vrf.postinst
+++ b/debian/vrf.postinst
@@ -29,18 +29,31 @@ do
 	dpkg-divert --divert ${DIVERT_DIR}/${f} --rename ${f}
 	sed -e 's/^PS1=/#PS1=/' ${DIVERT_DIR}/${f} > ${f}
 	cat >> ${f} <<EOF
-VRF=\$(ip vrf identify)
-[ -n "\${VRF}" ] && VRF=":\${VRF}"
+VRF=\$(vrf identify prompt)
 export VRF
 PS1='\${debian_chroot:+(\$debian_chroot)}\u@\h\${VRF}:\w\\\$ '
 EOF
 done
 
+if [ "$1" = configure ]; then
+	# If we have setcap is installed, try setting cap_dac_override+ep,
+	# which is needed to change VRF of a process
+	if command -v setcap > /dev/null; then
+		if setcap cap_dac_override+ep /usr/lib/cumulus/runvrf; then
+			echo "Successfully setcap cap_dac_override+ep on run vrf."
+		else
+			echo "setcap failed on runvrf"
+			exit 1;
+		fi
+	else
+		echo "setcap is not installed"
+		exit 1
+	fi
+fi
+
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
 #DEBHELPER#
-
-/bin/systemctl daemon-reload
 
 exit 0
